title: "Yehia Khaled — Data Engineering Portfolio"
name: "Yehia Khaled"
description: "DBA → Data Engineering & Cloud Platforms"
github_username: "YehiaKhaledAbouzeiid"
linkedin_username: "yehiakhaledabouzeiid"
